### ISSUE TITLE
ImportError: PyCapsule_Import could not import module "_ITKCommonPython"

### ISSUE THREAD

**Issue by Duchp1997** [RTKConsortium/RTK#435]
I am trying to write some code with RTK and ITK in Python. 

here is my code, very simple:

```
import os
import itk
from itk import RTKPython as rtk


def read_para(para_data_path):
    para_data_path = para_data_path
    # for i in sorted(os.listdir(para_data_path)):
    #     print(i)
    data = itk.imread(para_data_path)
    data_array = itk.GetArrayFromImage(data)
    return data_array


if __name__ == "__main__":
    file_path = r'air.dcm'
    read_para(file_path)
```

Here I choose `from itk import RTKPython as rtk` instead of `from itk import RTK as rtk` ,because i find there will bug if using 'RTK', and I can find the definition of 'RTKPython' in Pycharm,
 but when run it, something wrong happened.

here it is:
```

Traceback (most recent call last):
  File "/mnt/520_extend/dcp/CT_reco_py/read_data.py", line 16, in <module>
    from itk import RTKPython as rtk
  File "/home/dcp/anaconda3/lib/python3.8/site-packages/itk/RTKPython.py", line 13, in <module>
    from . import _RTKPython
ImportError: PyCapsule_Import could not import module "_ITKCommonPython"

```

I install itk and RTK with pip

here is the scripts:
```

pip install itk
pip install itk-rtk
```

and here are their version

```
itk                                5.2.1.post1
itk-core                           5.2.1.post1
itk-filtering                      5.2.1.post1
itk-io                             5.2.1.post1
itk-numerics                       5.2.1.post1
itk-registration                   5.2.1.post1
itk-rtk                            2.2.0
itk-segmentation                   5.2.1.post1
```

can someone have some ideas? thanks

**Comment by SimonRit** [comment]
Thanks for the report. RTK release is older than ITK's. Can you try a newer package compiled on the CI? It's available as an artifact in github actions, e.g., [here](https://github.com/SimonRit/RTK/actions/runs/1197123180).

**Comment by Duchp1997** [comment]
@SimonRit Thank you for your reply, I check the Github action, and actually yesterday my installed itk version has been `5.2.1.post1` as you can see before. But I notice that, in the .yml file in workflows. as you can see follows of a peice of whole code:
 ```
name: Build, test, package

on: [push,pull_request]

jobs:
  build-test-cxx:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        include:
          - os: ubuntu-20.04
            c-compiler: "gcc"
            cxx-compiler: "g++"
            itk-git-tag: "v5.2.1"
            cmake-build-type: "MinSizeRel"
          - os: windows-2019
            c-compiler: "cl.exe"
            cxx-compiler: "cl.exe"
            itk-git-tag: "v5.2.1"
            cmake-build-type: "Release"
          - os: macos-10.15
            c-compiler: "clang"
            cxx-compiler: "clang++"
            itk-git-tag: "v5.2.1"
            cmake-build-type: "MinSizeRel"
```
you set the ubuntu environment as 20.04,while my current environment is 18.04. and my python version is 3.8 created with Anaconda,
so my question is does the ubuntu version matter, and if it is necessary that the version is 20.04

Looking forward to your reply!
